image: gitpod/workspace-full
ports:
  - port: 3000
    onOpen: open-browser
tasks:
  - prebuild: bash -c "CYPRESS_INSTALL_BINARY=0 yarn install --frozen-lockfile"
    before: exit
    openMode: split-right
  - command: yarn start:dev
    openMode: split-right
  - command: yarn unit
    openMode: split-right
