image:
  file: .gitpod.dockerfile
ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - prebuild: mv /home/gitpod/node_modules . && exit
  - command: yarn start:dev
    openMode: split-bottom
  - command: yarn unit
    openMode: split-bottom
