image: gitpod/workspace-full
ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - prebuild: yarn install --frozen-lockfile
  - command: yarn start:dev
    openMode: split-bottom
  - command: yarn unit
    openMode: split-bottom
