image: gitpod/workspace-full
ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - prebuild: yarn install --frozen-lockfile && exit
  - command: yarn start:dev
    openMode: split-left
  - command: yarn unit
    openMode: split-right
